version: '3.8'

services:
  # MySQL 데이터베이스
  mysql:
    image: mysql:8.0
    container_name: gagym_mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-gagym1234}
      MYSQL_DATABASE: gagym
      MYSQL_USER: gagym
      MYSQL_PASSWORD: ${MYSQL_PASSWORD:-gagym1234}
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./mysql-utf8-setup.sql:/docker-entrypoint-initdb.d/01-setup.sql
      - ./create_attendance_table.sql:/docker-entrypoint-initdb.d/02-attendance.sql
      - ./create_inquiry_tables.sql:/docker-entrypoint-initdb.d/03-inquiry.sql
    restart: unless-stopped
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p${MYSQL_ROOT_PASSWORD:-gagym1234}"]
      interval: 30s
      timeout: 10s
      retries: 5

  # Spring Boot 백엔드
  backend:
    build: 
      context: .
      dockerfile: Dockerfile.backend.simple
    container_name: gagym_backend
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/gagym?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Seoul&allowPublicKeyRetrieval=true&useSSL=false
      - SPRING_DATASOURCE_USERNAME=gagym
      - SPRING_DATASOURCE_PASSWORD=${MYSQL_PASSWORD:-gagym1234}
      - EC2_PUBLIC_IP=${EC2_PUBLIC_IP}
    depends_on:
      mysql:
        condition: service_healthy
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

  # React 프론트엔드
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: gagym_frontend
    ports:
      - "80:80"
    depends_on:
      backend:
        condition: service_healthy
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  mysql_data:
